# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Publish

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
    
    - name: MSBuild
      run: msbuild Wastegate.Framework.Peripheral.sln -t:build -p:Configuration=Release -p:Platform=x64 -p:Platform=ARM -p:Platform=X86 -m -restore

    - name: Nuget restore pack
    - run: nuget restore Wastegate.Framework.Peripheral.sln
    
    - name: Nuget create pack.nuget
    - run: nuget pack pcf8574.nuspec
    
    - name: Nuget publish
    - run: nuget push -ApiKey ${{ secrets.GITHUB_TOKEN }}
